# Use root/example as user/password credentials

apiVersion: v1
kind: Pod
metadata:
   name: mySQLTest
spec:
   containers:
   - name: mytestdbv1
    image: mysql
    ports:
containerPort: 3306:3306
   imagePullPolicy: Always
     command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Clave01*
       MYSQL_DATABASE: dbTest1
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: '%'

