# Use root/example as user/password credentials

apiVersion: v1
kind: Pod
metadata:
   name: Tomcat
spec:
   containers:
   - name: mytestdbv1
    image: mysql
    ports:
containerPort: 8080:8080
   imagePullPolicy: Always
     command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Clave01*

