#FROM mysql
FROM 434c35b82b08
# Environment variables
ENV MYSQL_USER Clopez
ENV MYSQL_ROOT_PASSWORD Clave01*
ENV MYSQL_ALLOW_EMPTY_PASSWORD No
ENV MYSQL_RANDOM_ROOT_PASSWORD No

COPY mysqlslap /usr/bin
# Allows you to change the value of "max_allowed_packet"
#ADD ["mysqlconf/gatewaymy.cnf", "/etc/mysql/conf.d/conf_mysql.cnf"]

# Create Database
RUN	mkdir /usr/sql
RUN	chmod 644 /usr/sql
EXPOSE 3306/tcp
#ADD ["sql/sources.sql", "/usr/sql/sources.sql"]

#RUN /etc/init.d/mysql start  && \
#	mysql -u root -p ${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE testDB" 
#        mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE testDB" && \
#    	mysql -u root -p${MYSQL_ROOT_PASSWORD} -D lba < /usr/sql/sources.sql && \
#    	rm -rd /usr/sql && \
