SET ECHO OFF
SET SERVEROUTPUT ON SIZE 1000000
SET PAGESIZE 999
SET LINESIZE 132
SET WRAP OFF 
column Title format a22
column Summary format a15

--SPOOL $FILE

SELECT DISTINCT OWNER, OBJECT_NAME FROM DBA_OBJECTS
 WHERE OBJECT_TYPE = 'TABLE';

 --SPOOL OFF
--EXIT
--!EOF!
